//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpmBIMTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool exportModel_exportOptions_PurgeUnused {
            get {
                return ((bool)(this["exportModel_exportOptions_PurgeUnused"]));
            }
            set {
                this["exportModel_exportOptions_PurgeUnused"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool exportModel_exportOptions_Audit {
            get {
                return ((bool)(this["exportModel_exportOptions_Audit"]));
            }
            set {
                this["exportModel_exportOptions_Audit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_exportOptions_IncludeSheets {
            get {
                return ((bool)(this["exportModel_exportOptions_IncludeSheets"]));
            }
            set {
                this["exportModel_exportOptions_IncludeSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int exportModel_exportOptions_IncludeViews {
            get {
                return ((int)(this["exportModel_exportOptions_IncludeViews"]));
            }
            set {
                this["exportModel_exportOptions_IncludeViews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_exportOptions_IncludeRevitLinks {
            get {
                return ((bool)(this["exportModel_exportOptions_IncludeRevitLinks"]));
            }
            set {
                this["exportModel_exportOptions_IncludeRevitLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_exportOptions_IncludeCADLinks {
            get {
                return ((bool)(this["exportModel_exportOptions_IncludeCADLinks"]));
            }
            set {
                this["exportModel_exportOptions_IncludeCADLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_exportOptions_IncludeDWFLinks {
            get {
                return ((bool)(this["exportModel_exportOptions_IncludeDWFLinks"]));
            }
            set {
                this["exportModel_exportOptions_IncludeDWFLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_exportOptions_IncludeDecals {
            get {
                return ((bool)(this["exportModel_exportOptions_IncludeDecals"]));
            }
            set {
                this["exportModel_exportOptions_IncludeDecals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool exportModel_exportOptions_IncludeExportReport {
            get {
                return ((bool)(this["exportModel_exportOptions_IncludeExportReport"]));
            }
            set {
                this["exportModel_exportOptions_IncludeExportReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool exportModel_exportOptions_Compression {
            get {
                return ((bool)(this["exportModel_exportOptions_Compression"]));
            }
            set {
                this["exportModel_exportOptions_Compression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool exportModel_exportOptions_DisableWorksharing {
            get {
                return ((bool)(this["exportModel_exportOptions_DisableWorksharing"]));
            }
            set {
                this["exportModel_exportOptions_DisableWorksharing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_FloorPlans {
            get {
                return ((bool)(this["exportModel_includeView_FloorPlans"]));
            }
            set {
                this["exportModel_includeView_FloorPlans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_CeilingPlans {
            get {
                return ((bool)(this["exportModel_includeView_CeilingPlans"]));
            }
            set {
                this["exportModel_includeView_CeilingPlans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_StructuredPlans {
            get {
                return ((bool)(this["exportModel_includeView_StructuredPlans"]));
            }
            set {
                this["exportModel_includeView_StructuredPlans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_AreaPlans {
            get {
                return ((bool)(this["exportModel_includeView_AreaPlans"]));
            }
            set {
                this["exportModel_includeView_AreaPlans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_Sections {
            get {
                return ((bool)(this["exportModel_includeView_Sections"]));
            }
            set {
                this["exportModel_includeView_Sections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_Elevations {
            get {
                return ((bool)(this["exportModel_includeView_Elevations"]));
            }
            set {
                this["exportModel_includeView_Elevations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_Details {
            get {
                return ((bool)(this["exportModel_includeView_Details"]));
            }
            set {
                this["exportModel_includeView_Details"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_DraftingViews {
            get {
                return ((bool)(this["exportModel_includeView_DraftingViews"]));
            }
            set {
                this["exportModel_includeView_DraftingViews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_Legends {
            get {
                return ((bool)(this["exportModel_includeView_Legends"]));
            }
            set {
                this["exportModel_includeView_Legends"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_3DViews {
            get {
                return ((bool)(this["exportModel_includeView_3DViews"]));
            }
            set {
                this["exportModel_includeView_3DViews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_Renderings {
            get {
                return ((bool)(this["exportModel_includeView_Renderings"]));
            }
            set {
                this["exportModel_includeView_Renderings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_Walkthroughs {
            get {
                return ((bool)(this["exportModel_includeView_Walkthroughs"]));
            }
            set {
                this["exportModel_includeView_Walkthroughs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_Schedules {
            get {
                return ((bool)(this["exportModel_includeView_Schedules"]));
            }
            set {
                this["exportModel_includeView_Schedules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_PanelSchedules {
            get {
                return ((bool)(this["exportModel_includeView_PanelSchedules"]));
            }
            set {
                this["exportModel_includeView_PanelSchedules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportModel_includeView_ColumnSchedules {
            get {
                return ((bool)(this["exportModel_includeView_ColumnSchedules"]));
            }
            set {
                this["exportModel_includeView_ColumnSchedules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool quickSelect_selectionApplyToSelectionSet {
            get {
                return ((bool)(this["quickSelect_selectionApplyToSelectionSet"]));
            }
            set {
                this["quickSelect_selectionApplyToSelectionSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int quickSelect_selectionApplyToIncludeExclude {
            get {
                return ((int)(this["quickSelect_selectionApplyToIncludeExclude"]));
            }
            set {
                this["quickSelect_selectionApplyToIncludeExclude"] = value;
            }
        }
    }
}
